- name: Build image
  hosts: localhost
  vars:
    project_root: "{{ lookup('ansible.builtin.env', 'PWD') }}"
    polygon_path: "{{ project_root }}/polygon"
    repository_dest: "{{ polygon_path }}/package"
    repository_slug: "{{ lookup('ansible.builtin.env', 'REPO_SLUG') }}"
    repository_url: "git@github.com:htmlacademy/{{ repository_slug }}.git"
  tasks:
    - name: "Create polygon for building image"
      file:
        path: "{{ polygon_path }}"
        state: directory
        mode: "0755"

    - name: "Clone repository"
      git:
        repo: "{{ repository_url }}"
        dest: "{{ repository_dest }}"

    # TODO run npm install && npm run build in repository
    # (btw, postinstall hooks makes sense here)
    - name: "Install dependencies"
      npm:
        path: "{{ repository_dest }}"
        state: present

    - name: "Read version from config"
      set_fact:
        package_version: "{{ lookup('file', '{{ polygon_path }}/package/package.json') | from_json | json_query(jq) }}"
      vars:
        jq: "version"

    - name: "Copy Dockerfile"
      copy:
        src: "{{ project_root }}/ansible/files/{{ item }}"
        dest: "{{ project_root }}/polygon/{{ item }}"
      with_items:
        - Dockerfile
        - .dockerignore

    - name: "Build docker image"
      docker_image:
        name: "{{ repository_slug }}"
        tag: "{{ package_version }}"
        source: build
        build:
          rm: true
          path: "{{ polygon_path }}"
